name: Python Script Runner

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13.5'

      - name: Install dependencies
        run: |
          pip install Flask
          pip install Cloudant

      - name: Run Python script
        run: |
          python app.py
